<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mes</groupId>
        <artifactId>mes-backend</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>mes-process</artifactId>
    <name>mes-process</name>
    <description>工艺管理模块</description>
    <dependencies>
        <dependency>
            <groupId>com.mes</groupId>
            <artifactId>mes-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mes</groupId>
            <artifactId>mes-basic</artifactId>
        </dependency>
    </dependencies>
</project>
