port 26379
sentinel monitor mes-redis-master redis-master 6379 2
sentinel down-after-milliseconds mes-redis-master 5000
sentinel failover-timeout mes-redis-master 10000
sentinel parallel-syncs mes-redis-master 1
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
